### ISSUE TITLE
CSS Comb versus Stylelint

### ISSUE THREAD

**Issue by claytoncollie** [seothemes/genesis-starter-theme#25]
This is a general question.

I'm curious if you are using CCComb any more or if Stylelint has replaced that functionality, plus added more rules/lints.  Both config files look like what I need but maybe you can shed on light on whether I need both of them.  To me, if you use both, I could see wrapping them into a Composer script to run the comb then run the lint all with one command.

Thanks for the insight!

**Comment by seothemes** [comment]
Yes, currently using both. Stylelint is for Sass files and minified stylesheets while CSSComb is for formatting expanded stylesheets.

The theme uses expanded output by default because it's intended to be used for creating commercial themes where non-minified CSS is a requirement. For any other site I'd recommend switching to compressed output https://github.com/seothemes/genesis-starter-theme/blob/master/Gulpfile.js#L63

**Comment by claytoncollie** [comment]
Awesome. Thanks for the quick reply. I'm not building commercial themes, but for client specific projects.  That being said, I think your recommendation would be to switch to `compressed` output and only use only Stylelint on my Sass files.
